<!DOCTYPE HTML>
<html>
<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
</head>
<script src="/js/jquery.js" type="text/javascript"></script>
<style type="text/css">
#one{width:200px; height:180px; float:left}
#two{width:50px; height:180px; float:left}
#three{width:200px; height:180px; float:left}
.btn{width:50px; height:30px; margin-top:10px; cursor:pointer;}
</style>

<script type="text/javascript">

function sub(){
	var info=document.getElementById("txtHint").innerText;   
    if(info.trim()!='新增推免院系合法'){
    	alert("请认真添加新增院系信息");
    }else{
		document.forms["f"].submit();
	}	
}
	
</script>
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #F8F9FA;
}
-->
</style>

<script src="/js/sdeqtunique.js"></script>
<link href="/images/skin.css" rel="stylesheet" type="text/css" />
<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
  <tr>
    <td width="17" height="29" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td width="935" height="29" valign="top" background="/images/content-bg.gif"><table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
      <tr>
        <td height="31"><div class="titlebt">增加院系</div></td>
      </tr>
    </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td height="71" valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="100%" height="138" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td height="13" valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td class="left_txt">当前位置：特权信息管理-增加推免专业</td>
          </tr>
          <tr>
            <td height="20"><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#CCCCCC">
              <tr>
                <td></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td><table width="100%" height="55" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td width="10%" height="55" valign="middle"><img src="/images/title.gif" width="54" height="55"></td>
                <td width="90%" valign="top"><span class="left_txt2">在这里，管理员可以增加新增硕士授予权的研究生专业</span><br>
                          <span class="left_txt2">等以及网站</span><span class="left_txt3">不能申请已存在的专业</span><span class="left_txt2">。 </span></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td><table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="nowtable">
              <tr>
                <td class="left_bt2">&nbsp;&nbsp;&nbsp;&nbsp;新增院系信息</td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td>

            <form action="/school/addsdept" method="post" name=f>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr><td colspan=4><hr height=2 color=white></td></tr>
              <tr>
                <td width="20%" height="30" align="right" bgcolor="#f2f2f2" class="left_txt2">院系名称：</td>
                <td width="3%" bgcolor="#f2f2f2">&nbsp;</td>
                <td width="32%" height="30" bgcolor="#f2f2f2"><input name="sdename"  required="required" type="text" onkeyup="showHint(this.value)" size="30" /></td>
                <td width="45%" height="30" bgcolor="#f2f2f2" class="left_txt"><span style="color:#0000ff;" id="txtHint"></span></td>
              </tr>
              <tr><td colspan=4><hr height=2 color=white></td></tr>
              <tr>
                <td width="20%" height="30" align="right"  class="left_txt2">简要介绍：</td>
                <td width="3%" >&nbsp;</td>
                <td width="32%" height="30" ><textarea name="dis" cols=27 placeholder="可以为空" ></textarea></td>
                <td width="45%" height="30"  class="left_txt">填写该专业详细信息</td>
              </tr>
              
              
              <tr><td colspan=4><hr height=4 color=white></td></tr>
              
            
              
        
       
              <tr>
                <td height="30" colspan="4" class="left_txt" align="center">
              <input type="button" value="确认添加" onclick="sub()"  /></td>
                 </form>  
            </tr>
                </td>
                </tr>
            </table></td>
            
          

          </tr>
        </table>
          </td>
      </tr>
    </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
      <td height="17" valign="top" background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17" /></td>
    <td background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>

</body>
