<!DOCTYPE HTML>
<html>
<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
</head>
<style>

#divv{height:80px;overflow:hidden;}

.pczt_pingfen_jhxs_news1{ width:450px;  background:#edfafd; padding-top:2px; padding-bottom:2px; margin:0 auto;}
.pczt_pingfen_jhxs_xian{ width:450px;  margin:0 auto; border:1px dashed #a8d1dd; border-left:none; border-right:none;}
.pczt_pingfen_jhxs_noxian{ width:450px;  margin:0 auto; border:none;}
.pczt_pingfen_jhxs_wenzi{color:#185881; text-align:center; line-height:30px;}
.pczt_pingfen_jhxs_wenzi2{line-height:22px; font-size:12px; text-indent:2em; color:#185881;}
</style>
<script type="text/javascript" src='/js/score.js'></script>
<script src="/files/log.js" async="" charset="utf-8"></script><script src="/files/key.htm"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<link rel="stylesheet" href="/files/style.css">
    <script src="/files/jquery-1.js" type="text/javascript"></script>
    <script type="text/javascript">
    function opennew(id,scid)
    {
    window.open("/news/showone?scid="+scid+"&id="+id,null,"width=700,height=400,toolbar=no,top=100,left=400,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no")
    }
    var jq=jQuery.noConflict();
    </script>
<link rel="stylesheet"  href="/css/webwidget_scroller_tab.css" type="text/css" />
        <script type='text/javascript' src='/js/jquery-1.3.2.min.js'></script>
        <script type='text/javascript' src='/js/webwidget_scroller_tab.js'></script>
        <script language="javascript" type="text/javascript">

            $(function() {
                $(".webwidget_scroller_tab").webwidget_scroller_tab({
                    scroller_time_interval: '5000',
                    scroller_window_padding: '10',
                    scroller_window_width: '350',
                    scroller_window_height: '200',
                    scroller_head_text_color: '#0099FF',
                    scroller_head_current_text_color: '#666',
                    directory: 'images'
                });
            });
        </script>
<link href="/images/skin.css" rel="stylesheet" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #EEF2FB;
}
-->
</style>
<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="17" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td valign="top" background="/images/content-bg.gif"><table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
      <tr>
        <td height="31"><div class="titlebt">欢迎界面</div></td>
      </tr>
    </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td colspan="2" valign="top">&nbsp;</td>
        <td>&nbsp;</td>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td colspan="2" valign="top"><span class="left_bt">感谢使用研究生推免管理系统程序</span><br>
              <br>
            <span class="left_txt">&nbsp;<img src="/images/ts.gif" width="16" height="16"> 提示：<br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎进入高校管理员端！本页面包括：</span><span class="left_ts">统计图表、动态通知等</span><span class="left_txt">欢迎了解<br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;管理员后台主要包括三大模块：学校信息管理，学生推免管理，特权信息管理</span><span class="left_txt"><br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;管理员可以修改高校信息,发布通知,处理推免信息，打印成绩单，添加新院系，处理学生评论及回复、修改密码等</span><span class="left_txt"><br>
         
        
</span></td>
        <td width="7%">&nbsp;</td>
        <td width="40%" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" class="line_table">
          <tr>
            <td width="3%" height="27" background="/images/news-title-bg.gif" class="left_bt2">&nbsp;&nbsp;最新动态</td>
            <td width="97%"  colspan=2 background="/images/news-title-bg.gif" ></td>
          </tr>
          <form action="/school/addsdept" method="post">
          <tr>
          <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
             <td colspan=3>
    <div id="demo" onmouseover="clearInterval(timer)" onmouseout="timer=setInterval(mar,30)" style="overflow:hidden; height:140px; width:100%;">
<div id="demo1" style="height:100%;" >
           			<div class="pczt_pingfen_jhxs_news1" >
                    	<div class="pczt_pingfen_jhxs_xian">
                        	
                            <p class="pczt_pingfen_jhxs_wenzi">
							    <table width="100%">
     <tr bgcolor="#00ffff"><td colspan=3 align="center" height="25"  style="font-size:14px; font-weight:600; letter-spacing:2px;">高校研究生推免最新消息</td></tr>
       <?php foreach ($this->news as $item){
       	$id=$item['id'];
       	$scid=$item['scid'];
	echo "
  <tr>
    <td align=left><a href='#' style='color:#0000FF' onClick=opennew('$id','$scid')>".$item['title']."</a></td>
	
    <td style='font-size:14px;'> ".$item['time']."</td>
	<td style='font-size:10px;'> ".$item['issuer']."</td> 
  </tr>
  ";

  }?>
    
    
    </table>
							
							</p>
                        </div>
                    </div>
                    <div class="pczt_pingfen_jhxs_xian">
                      
                      <p class="pczt_pingfen_jhxs_wenzi">
					     <table width="100%">
        
       <?php foreach ($this->news as $item){
       	$id=$item['id'];
       	$scid=$item['scid'];
	echo "
  <tr>
    <td align=left><a href='#' style='color:#0000FF' onClick=opennew('$id','$scid')>".$item['title']."</a></td>
	
    <td style='font-size:14px;'> ".$item['time']."</td> 
    <td style='font-size:10px;'> ".$item['issuer']."</td> 
  </tr>
  ";

  }?>

    </table>					  
					  </p>
                    </div>
          <div id="demo2"></div>
          </div>
			</div>
    
    </td>
          <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
            
          </tr>
          </form>
          <tr>
            <td height="5" colspan="2">&nbsp;</td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td colspan="2">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td colspan="2" valign="top"><!--JavaScript部分-->

              <div class="webwidget_scroller_tab" id="webwidget_scroller_tab">
          <div class="tabContainer">
            <ul class="tabHead">
              <li class="currentBtn"><a href="javascript:;">折线图</a></li>
              <li><a href="javascript:;">扇形图</a></li>
              <li><a href="javascript:;">柱状图</a></li>
            </ul>
          </div>
          
          <div class="tabBody">
            <ul>
              <li class="tabCot">
                 <img src="/graph/line.php"  width =340 height=180>
              </li>
              <li class="tabCot">
                
                <img src="/graph/pie.php" width =320 height=150>
                
              </li>
              <li class="tabCot">
                 <img src="/graph/bar.php" width =350 height=170>
              </li>
            </ul>
            <div style="clear:both"></div>
          </div>
          <div class="modBottom"> </div>
        </div>
            
        </td>
        <td>&nbsp;</td>
        
        
        
        <td valign="top"><table width="100%" height="144" border="0" cellpadding="0" cellspacing="0" class="line_table">
          <tr>
            <td width="7%" height="27" background="/images/news-title-bg.gif"><img src="/images/news-title-bg.gif" width="2" height="27"></td>
            <td width="93%" background="/images/news-title-bg.gif" class="left_bt2">最新消息</td>
          </tr>
          <tr>
            <td height="102" valign="top">&nbsp;</td>
            <td height="102" valign="top"><label></label>
              <label>
              <textarea name="textarea" cols="78" rows="8" class="left_center">	长春大学有着悠久的办学历史，这里曾是1938年伪满洲国最高学府长春建国大学的校址，1946年国民党统治时期在此设立长春大学农学院。学校现有20个教学院部，50个本科专业，涵盖经济学、法学、教育学、文学、理学、工学、农学、医学、管理学、艺术学十大学科门类。全日制在校学生15455人。
			  </textarea>
              </label></td>
          </tr>
          <tr>
            <td height="5" colspan="2">&nbsp;</td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td height="40" colspan="4"><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#CCCCCC">
          <tr>
            <td></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td width="2%">&nbsp;</td>
        <td width="51%" class="left_txt"><img src="/images/icon-mail2.gif" width="16" height="11"> 服务邮箱：leadershanzhi@163.com<br>
              <img src="/images/icon-phone.gif" width="17" height="14"> 联系电话：15543261882</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="bottom" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
    <td background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17"></td>
    <td valign="bottom" background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>
</body>
<script>
var t=getid("demo"),t1=getid("demo1"),t2=getid("demo2"),sh=getid("show"),timer;
t2.innerHTML=t1.innerHTML;
function mar(){
if(t2.offsetTop<=t.scrollTop)
t.scrollTop-=t1.offsetHeight;
else
t.scrollTop++;
}
timer=setInterval(mar,30);
function getid(id){
return document.getElementById(id);
}
</script>
<script>
var c,_=Function;
with(o=document.getElementById("divv")){ innerHTML+=innerHTML; onmouseover=_("c=1"); onmouseout=_("c=0");}
(F=_("if(#%18||!c)#++,#%=o.scrollHeight>>1;setTimeout(F,#%18?15:400);".replace(/#/g,"o.scrollTop")))();
</script>

