<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
<title>
	吉林省_计算机类_研究生推免信息
</title>
<meta name="robots" content="all" />

<link rel='stylesheet' type='text/css' href='/css/common.css'/>
<link rel='stylesheet' type='text/css' href='/css/bbb.css'/>

<script type="text/javascript" src='/js/jquery.js'></script>
<script type="text/javascript" src='/js/score.js'></script>




<script type="text/javascript">
   function submitForm(){
	   var info=document.getElementById("test").innerText;   
       if(info.trim()=='您各项成绩符合推免要求'){
          f.submit();
       }else{
          alert("请务必完善推免信息,需有(符合推免要求)的字样提示！");
       }    
   }



</script>
</head>

<body>

<style type="text/css">
html,body{ margin:0; padding:0;}
/*topNav layout*/
#nav_top{ font:12px/1.5 '\5FAE\8F6F\96C5\9ED1','\5B8B\4F53', Arial, Helvetica, sans-serif; background: url("http://t1.chsi.cn/yz/images/base/nav_top_bg.png") repeat-x left top; text-align:left;  border-bottom:solid 1px #c7c7c7; }

.topNav{ height:35px; line-height:35px; font-size:12px; background:#367bb9;  margin-bottom:10px; }

.topNav950{ margin:0 auto; width:950px; text-align:left; clear:both;}
.topNav_l{ float:left; width:800px; height:35px; overflow:hidden; line-height:35px;}
.topNav_l a { float: left;    padding: 0 8px;	display:inline;  }
.topNav_l a:link, .topNav_l a:visited { color:#333;  text-decoration: none;}
.topNav_l a:hover {   text-decoration:underline;}
.topNav_r {display: inline;    float: right;    position: relative;    width: 150px;   z-index: 999;}

/*LoginAfter*/
#yz_NavLoginAfter{  position:relative; z-index:10; float:right;}
#yz_NavLoginAfter .userInfo-wrap{ background-color: #5195D2;  border: 1px solid #4E88AF;   box-shadow: 0 3px 2px 0 #6298C9; color:#fff; font-size: 12px;  padding: 0px 10px 0px 15px;  margin-right:0px; display:inline; height:33px; line-height:33px; float:left; width:108px; text-align:left; text-indent:15px; }
#yz_NavLoginAfter .userInfo-wrap a{ display:block; width:108px; overflow:hidden; text-overflow: ellipsis;white-space: nowrap; max-width:108px; color:#FFF; font-weight:bold; }
#yz_NavLoginAfter .userInfo-wrap after{content:"...";}
#yz_NavLoginAfter ul, #yz_NavLoginAfter li{ list-style:none; margin:0px; padding:0px;}
#yz_logined{ position:relative; height:33px; }
#yz_suggest_wrap{ position:absolute; top:40px; z-index:1000; width:130px;  right:0px; background:#fff; border:solid #ddd 1px; padding:10px 0px; margin:0px;}
#yz_suggest_wrap li{ margin:0px; padding:0px; color:#333;   height: 29px; line-height: 29px;    }
#yz_suggest_wrap li span {    border-bottom: 1px dashed #DCDDDD;    display: block;	width: 110px;	margin:0 10px;	overflow:hidden;}
#yz_suggest_wrap li a{ display:block; margin:0px; padding:0px; cursor:pointer;}
#yz_suggest_wrap li a:hover{ background:#F2F2F2; font-weight:bold; color:#333; }
.ntes-nav-select-arr {	font-family:Verdana;    display:block;	position: absolute;    left: 15px;    top: 18px;	width:0px;	height:0px;	overflow:hidden;	border:4px solid #5195D2;	border-width:4px 4px 0px 4px;	border-color:#fff #5195D2; }
.ntes-nav-select-unfold .ntes-nav-select-arr{  	transform: rotate(180deg);    transition: all 0.25s ease 0s;}

/*LoginBefore*/	
#yz_NavLoginBefore{ float:right;  position:relative; z-index:10; }
#yz_NavLogin a{ float:left; margin-right:15px; display:block; height:34px;  line-height:34px; color:#333;}
#yz_NavLogin a.loginIn {  background-color: #5195D2;  border: 1px solid #4E88AF;   box-shadow: 0 3px 2px 0 #6298C9; font-size: 12px;    padding: 0 15px; color:#FFF;}
#yz_NavLogin a.loginIn:hover{ text-decoration:none;}
#yz_login_wrap{ background:#fff; padding:5px 20px; position:absolute; z-index:999; top:39px; z-index:1000; right:0px;   border:1px solid #CDCDCD; box-shadow: 8px #CDCDCD}
#yz_login_wrap table{ width:230px; border:0; color:#333; margin:0px;}
#yz_login_wrap table td{  vertical-align:middle; padding:5px 0; }
#yz_login_wrap  hr{ border:none; border-bottom:solid 1px #ccc; height:0px; margin:0px 0px 10px 0px; }
#errormsg{color:#F00; padding-bottom:5px; line-height:16px; margin:0px;}
#loginBefore_link{ margin:0px; padding:0px; line-height:28px; }
#yz_login_wrap tr.login-hd td{ padding:0px; height:30px; line-height:30px;}
#yz_login_wrap tr.login-hd a{ color:#5c85ad; margin-right:0px; display:inline; float:none;}

#yz_loginframe_username{ background:url(http://t3.chsi.cn/yz/images/base/login_icon.png) no-repeat 5px 7px; line-height:30px; width:195px; height:30px; font-size:12px; padding-left:30px; padding-right:5px; border: 1px solid #CCCCCC; }
#yz_loginframe_password{ background:url(http://t3.chsi.cn/yz/images/base/login_icon.png) no-repeat 5px -33px; line-height:30px; width:195px; height:30px; padding-left:30px; padding-right:5px; border: 1px solid #CCCCCC;}
#yz_loginframe_authcode{   width:90px; height:30px; padding-left:3px; line-height:30px; border: 1px solid #CCCCCC;}
#nav_top p.bread_nav{ line-height:38px; height:38px;}
.yz_loginframe_btn{    background-color: #5195D2;	 background-image: -moz-linear-gradient(center top , #5ea2df, #72a2ce);      border: 1px solid #4E88AF;    color: #FFFFFF;    cursor: pointer;    float: left;    font-size: 14px;    font-weight: bold;    height: 34px;    width: 230px;	}
.yz_loginframe_btn:hover {    background-color: #6298C9; background-image: -moz-linear-gradient(center top , #5195D2, #6298C9);    border: 1px solid #6298C9;}
.topNav input[type="text"], .topNav input[type="password"] {	resize: none;    border: 1px solid #CCCCCC;    border-radius: 3px 3px 3px 3px;    color: #555555;
    display: inline-block;    font-size: 12px;    padding-left: 3px;    vertical-align: middle;}
#nav_top input[type="text"]:hover,#nav_top input[type="password"]:hover {    border-color: rgba(82, 168, 236, 0.8);    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1) inset, 0 0 8px rgba(82, 168, 236, 0.6);    outline: 0 none;}


</style>




<script type="text/javascript">
	function getVimg(){
		if($("#vimg").attr("src").toString().indexOf("IMG")==-1){
			$("#ImgLoading").show();
			$("#vimg").attr("src","/ValidatorIMG.JPG?ID=" + Math.random()*10000);
			$("#vimg").load(function(){ $("#ImgLoading").hide();$("#vimg").show(); })
		}
		}
			
</script>

<div class="topNav" id="nav_top">
<div class="topNav950">
    <div class="topNav_l"><a href="/">首页</a><a href="/kyzx/zcdh/" target="_self">政策</a><a href="/kyinfo/" target="_self">资讯</a><a href="/sch/" target="_self">院校信息</a><a href="/zyk/" target="_self">专业知识库</a></div>
    <div class="topNav_r">
    <div class="nav">
    
    
    
    





<?php 
   session_start();
   $name=$_SESSION['loginuser']['name'];
?>

<div id="yz_NavLoginAfter"  style="display:block">
  <div tabindex="0"   id="yz_logined">
      <span class="userInfo-wrap"><a href="/user/" id="user_info_name"><?php echo $name?></a><em class="ntes-nav-select-arr"></em></span>
      <div  id="yz_suggest_wrap" style="display:none">
            <ul class="clearfix" id="yz_logined_suggest">
            <li><a href="/student/stuenter" ><span>返回主页面</span></a></li>       
            <li><a href="/global/exit"><span>安全退出</span></a></li>
            </ul>
        </div>
    </div> 
</div>
    
    
    
    



<?php 
session_start();
$name=$_SESSION['loginuser']['name'];
$id=$_SESSION['loginuser']['id'];
$zy=$_SESSION['loginuser']['zyscore'];
$dy=$_SESSION['loginuser']['dyscore'];
$phone=$_SESSION['loginuser']['phone'];
$sum=$zy+$dy;
?>






    
    
    </div>
    </div>
  </div>
</div>



<script type="text/javascript">
$("#nav_top").ready(function(){		
  $("#yz_login_a").live("mouseenter",function(){$("#yz_login_wrap").toggle(true); })
  $("#yz_login_a").live("click",function(){$("#yz_login_wrap").toggle(); return false; })
  $("#yz_logined").live("mouseenter",function(){$(this).addClass("ntes-nav-select-unfold"); $("#yz_suggest_wrap").show();}); 
  $("#yz_suggest_wrap").live("mouseenter",function(){$("#yz_logined").data("flg",true); })
  $("#yz_suggest_wrap").live("mouseleave",function(){$("#yz_logined").removeClass("ntes-nav-select-unfold"); $(this).hide(); $("#yz_logined").data("flg",false);})
/*
 $("#yz_login_wrap").live("mouseleave",function(){setTimeout(function(){ $("#yz_login_wrap").toggle(false);},400); })
 */
  $("#yz_logined").live("mouseleave",function(){
	if($("#yz_suggest_wrap").get(0).style.display=="none"){ return;}
	setTimeout(function(){ if(!!!$("#yz_logined").data('flg')){$("#yz_logined").removeClass("ntes-nav-select-unfold"); $("#yz_suggest_wrap").hide();} },400)									  			 })
  
	$("#yz_navLogout").live("click",function(){
		$.post("/user/logout.do",{random:Math.random()*10000},function(){
			$(".nav").load("/common/nav_login.jsp",function(){
				window.location.reload();
			});
			
		})
		return false;
	});
	
	$("#yz_loginframe_btn").live("click",function(){
		var name = $.trim($("#yz_loginframe_username").val());
		var pass = $.trim($("#yz_loginframe_password").val());
		var chek = $.trim($("#yz_loginframe_authcode").val());
		if(name==""){
			$("#yz_loginframe_username").css({"border-color":"#FFB5B5","background-color":"#FFEEEE"}).focus();
			return false;
		}
		if(pass==""){
			$("#yz_loginframe_password").css({"border-color":"#FFB5B5","background-color":"#FFEEEE"}).focus();
			return false;
		}
		if(chek==""){
			$("#yz_loginframe_authcode").css({"border-color":"#FFB5B5","background-color":"#FFEEEE"}).focus();
			return false;
		}
		$.post("/user/loginpub.do",{j_username:name,j_password:pass,CHKNUM:chek,random:Math.random()*10000},function(data){
			var j = eval(data);
			if(j.succ=="true"){
				$(".nav").load("/common/nav_logout.jsp",function(){
					window.location.reload();											 
				});
				
			}else{
				$("#vimg").attr("src","/ValidatorIMG.JPG?ID=" + Math.random()*10000);
				$("#yz_loginframe_authcode").val("");
				$("#errormsg").html(j.msg).fadeIn("fast");
			}
		});
		
		return false;
		
	});
	


	$("#yz_login_wrap :input[type!='button']").live("blur",function(){
		if($.trim($(this).val())==""){
			$(this).css({"border-color":"#FFB5B5","background-color":"#FFEEEE"});
		}else{
			$(this).css({"border-color":"#CCCCCC","background-color":"#fff"});
		}
	});
	
  
});



</script>

<script type="text/javascript">

document.onmouseup=function(event){
	var e=event ||window.event;
 	var elm=e.srcElement || e.target;
	do{ 
	if(elm.id == "yz_login_a") {return true;}
	if(elm.id =="yz_login_wrap"){ return;};
	elm = elm.parentNode;
	}
	while(elm.parentNode)
	$("#yz_login_wrap").toggle(false);
	}
	
</script>

<style type="text/css">
.clearfix:before, .clearfix:after, .container_24:before, .container_24:after {
    content: ".";
    display: block;
    font-size: 0;
    height: 0;
    line-height: 0;
    overflow: hidden;
    visibility: hidden;
    width: 0;
}
.clearfix:after, .container_24:after {
    clear: both;
}

.container_24 {
    margin-left: auto;
    margin-right: auto;
    width: 960px;
}
.container_24 .grid_24 {
    width: 950px;
}

 .grid_24 {
     display: inline;
    float: left;
    margin-left: 5px;
    margin-right: 5px;
}
 .cur_position {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #FBFBFB;
    background-image: linear-gradient(to bottom, #FEFEFE, #E7E7E7);
    border-color: #CCCCCC #CCCCCC #999999;
    border-image: none;
    border-style: solid;
    border-width: 1px;
    margin-bottom: 10px;
    padding-left: 10px;
	font-family:'微软雅黑','宋体',Arial,Helvetica,sans-serif;
	 height: 36px;
    line-height: 36px;
}  
.cur_position a {
    color: #000000;
}
</style>
<div class="container_24 clearfix" id="header">
  <div class="grid_24 clearfix"><img align="middle" alt="吉林省_计算机类_研究生推免信息" src='/images/ztuimian_banner.png' title='高校研究生推免系统学生端' /></div>
  <div class="grid_24 clearfix">
   <div class="cur_position">当前位置：<a  href="#">高校研究生推免管理</a> &gt;  申请推免高校</div>
  </div>
</div>

<div class="whiteBG">
<div id="main_page">

	<div class="tjMain">
<div class="tjMainTitle">高校研究生推免学生端</div>
		<div class="tjMainBtm">
        

<div class="tjtop"></div>
<div class="tjrepeat">

<div class="tjleft">		
				

			<ul id="menu">
				<li class="title">高校研究生推免系统<br />
学生管理</li>
	            <li class="content" ><a id="step_1" href="/student/stuenter">查看推免记录</a></li>
				<li class="content" ><a id="step_1" href="/student/stuscore">查看成绩信息</a></li>
				<li class="content" ><a id="step_2" href="/news/stushow">查询通知信息</a></li>
				<li class="content" ><a id="step_2" href="/school/showschools">查看高校信息</a></li>
				<li class="content" ><a id="step_3" href="/school/stuselect">选择推免学校</a></li>
				<li class="content" ><a id="step_4" href="/student/stualterpw">个人密码修改</a></li>
				<li class="content" ><a id="step_5" href="/student/stualter">基本信息修改</a></li>
			</ul>

			</div>
<div class="tjright" align="center">
		


<table width="594" border="0" cellpadding="4" cellspacing="0" style="margin:10px auto;">
      <tr bgcolor="#FFFFFF">
        <th align="center" height="25" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">当前待录取状态</th>
  </tr>
  <tr bgcolor="#FFFFFF"><td valign="top"><table width="100%" border="0" cellpadding="4" cellspacing="1" style="background-color:#AAA;">
		  	<tr bgcolor="#FFFFFF" style="font-weight:600">
        <td bgcolor="#ffffff">推免高校</td>
        <td bgcolor="#ffffff">录取状态</td>
       
  </tr>
  <?php 
  $re=$this->tmresult;
  if($re!="0"){
 echo "
  <tr bgcolor=#FFFFFF>		
        <td bgcolor=#ffffff>".$re."</td>
        <td bgcolor=#ffffff>已被录取</td>   
  </tr>";
  		
   }?>

</table>
	</td>
  </tr>
</table>
<form name="f" action="/student/applysc">
<table width="594" border="0" align="center" cellpadding="4" cellspacing="1" style="background-color:#AAA;text-align:left">
      <tr bgcolor="#FFFFFF">
        <th colspan="2" align="center" height="30" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">申请推免学校</th>
  </tr>
  
      <tr bgcolor="#FFFFFF">
        <td bgcolor="#ffffff">考生姓名</td>
        <td bgcolor="#ffffff" style="color:#FF3300"><?php echo $name?></td>
      </tr>
      <tr bgcolor="#FFFFFF">
        <td bgcolor="#ffffff">身份证号</td>
        <td bgcolor="#ffffff" style="color:#FF3300"><?php echo $id?></td>
      </tr>
      <tr bgcolor="#FFFFFF">
        <td bgcolor="#ffffff">成绩纵览</td>
        <td bgcolor="#ffffff" style="color:#FF3300"><?php echo "德育:_".$dy.";  智育:_".$zy.";  总分:_".$sum?></td>
      </tr>
      <tr bgcolor="#FFFFFF">
        
  </tr>
      
      <tr bgcolor="#FFFFFF">
        <td bgcolor="#FFffee">招生单位</td>
        <td bgcolor="#FFffee">
            <select  class="text" name="se" onchange=sdept(document.f.se.value)><option value="">___请选择___</option>
                <?php foreach ($this->scs as $item){  
                	echo "<option>".$item['scname']."</option>";
                }?>
     		</select>    
     		<select id="ttt" name="ttt" onchange="tScore(document.f.se.value)">
     		
     		</select>
     		</td>
      </tr>
      
      <tr bgcolor="#FFFFFF">
	        <td bgcolor="#FFffee">审查结果</td>
	        <td bgcolor="#FFffee" style="color:#FF3300; line-height:20px;"><font id="test" color="#0000FF"></font></td>  
      </tr>	

	<tr bgcolor="#FFFFFF">
	        <td bgcolor="#FFffee">备注</td>
	        <td bgcolor="#FFffee" style="color:#FF3300; line-height:20px;"><input type="text" placeholder="按招生单位要求填写"  name="bz" maxlength="80" value=""/>
	 <font color="#D8D8D8">按招生单位要求填写,最多50个字符</font></td>  
      </tr>	 
       <tr bgcolor="#FFFFFF">
        <td bgcolor="#FFffee">联系电话</td>
        <td bgcolor="#FFffee" style="color:#FF3300; line-height:20px;"><input type="text" name=""  value="<?php echo $phone?>"/> 
 <font color="#D8D8D8">注意：这是高校与推免生联系的重要渠道，请准确填写。
　　</td>  
      </tr>	  
      <tr bgcolor="#FFFFFF">
        <td colspan="2">
          <div align="center">
            	<input type="button" name="add1" value="提交推免申请" onclick="submitForm()" class="button">&nbsp;&nbsp;<font color="#FF0000"></font>
          </div>        
          </td>
  </tr>
  
      <tr bgcolor="#FFFFFF">
	        <td bgcolor="#FFeeFF" colspan=2></td>
	        
      </tr>	 

</table>
</form>


</div>
<div class="clearFloat"></div>
<!--end tjrepeat--></div>

<div class="tjbottom"></div>

</div>
</div>
</div>

<iframe width="950" height="93" src="/index/foot" scrolling="no" frameborder="0"></iframe>
</div>
</body>
</html>	