<!DOCTYPE HTML>
<html>
<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
</head>
<script type="text/javascript">
  function checkpw(){
    if(document.f.pw.value!==document.f.pwx.value){
       alert("新密码需与原密码一致");
       document.f.pwx.value="";
    }
  }
</script>
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #F8F9FA;
}
-->
</style>

<link href="/images/skin.css" rel="stylesheet" type="text/css" />
<body>
<br/><br/><br/><br/>
<table width="70%" border="0" cellpadding="0" cellspacing="0" align="center">
  <tr>
    <td width="17" height="29" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="17" height="29" /></td>
    <td width="935" height="29" valign="top" background="/images/content-bg.gif"><table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
     
    </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td height="71" valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="100%" height="138" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td height="13" valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td class="left_txt">当前位置：高校管理员注册</td>
          </tr>
          <tr>
            <td height="20"><table width="100%" height="1" border="0" cellpadding="0" cellspacing="0" bgcolor="#CCCCCC">
              <tr>
                <td></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td><table width="100%" height="55" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td width="10%" height="55" valign="middle"><img src="/images/title.gif" width="54" height="55"></td>
                <td width="90%" valign="top"><span class="left_txt2">高校注册界面</span><br>
                          <span class="left_txt2">包括</span><span class="left_txt3">登录名称，登录密码，确认密码，验证码。</span></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td><table width="100%" height="35" border="0" cellpadding="0" cellspacing="0" class="nowtable">
              <tr>
                <td class="left_bt2">&nbsp;&nbsp;&nbsp;&nbsp;注册内容</td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
			<form name="f" method="POST" action="/manager/addman">
              <tr>
                <td width="20%" height="34" align="right" bgcolor="#f2f2f2" class="left_txt2">登录名称：</td>
                <td width="3%" bgcolor="#f2f2f2">&nbsp;</td>
                <td width="39%" height="34" bgcolor="#f2f2f2"><input name="scid" type="text" size="34" /></td>
                <td width="38%" height="34" bgcolor="#f2f2f2" class="left_txt">高校名称简写字母组合</td>
              </tr>
              <tr>
                <td height="34" align="right" class="left_txt2">登录密码：</td>
                <td>&nbsp;</td>
                <td height="34"><input type="password" name="pw" required="required" pattern="^[a-zA-Z0-9]{4,8}$" title="密码由4至8位的字母或数字组成" height="18" name="pw" size="34" /></td>
                <td height="34" class="left_txt">字母数字组成的6-8位</td>
              </tr>
			  <tr>
                <td height="34" align="right" bgcolor="#f2f2f2" class="left_txt2">确认密码：</td>
                <td bgcolor="#f2f2f2">&nbsp;</td>
                <td height="34" bgcolor="#f2f2f2"><input type="password" name="pwx" required="required" height="18" onChange="checkpw()" size="34" /></td>
                <td height="34" bgcolor="#f2f2f2" class="left_txt">请与上个表单输入一致</td>
              </tr>
			  <tr>
                <td height="34" align="right" class="left_txt2">预留字段：</td>
                <td>&nbsp;</td>
                <td height="34"><input type="text" height="18" required="required" name="point" size="34" /></td>
                <td height="34" class="left_txt">不可更改！找回密码时使用</td>
              </tr>
              
              <tr>
                <td height="17" colspan="4" align="center" >
				<input type="submit" value="确定注册"  />
				
				</td>
              </tr>
			  </form>
            </table></td>
          </tr>
        </table>
         </td>
      </tr>
    </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
      <td height="17" valign="top" background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17" /></td>
    <td background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>

</body>

