<link rel='stylesheet' type='text/css' href='/css/aa.css'/>
<link rel='stylesheet' type='text/css' href='/css/bb.css'/>
<link rel='stylesheet' type='text/css' href='/css/cc.css'/>
<div class="footer" id="footer" align="center"> <a href="" target="_blank">[ CHSI首页 ]</a> -- <a href="" target="_blank">[ 中心简介 ]</a> -- <a href="" target="_blank">[ 联系我们 ]</a> 
-- <a href="" target="_blank">[ 版权声明 ]</a> -- <a href="" target="_blank">[ 网站地图 ]</a> -- <a href="" target="_blank">[ 宣传代理 ]</a> -- <a href="" target="_blank">[ 我要投稿 ]</a> <br />
    主管单位：高校研究生推免管理委员会　　主要设计：<a href="" target="_blank">长春大学计算机学院单智</a>　　<a href=""  target="_blank">学号：271040219</a><br />
   主要内容：吉林省计算机类研究生推免管理系统　　服务热线：15543261882　　　邮箱：421170702@qq.com</div>