<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>研究生推免首页</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='/css/d.css' type="text/css" rel="stylesheet" />
<meta name="robots" content="all" />
<style>

.shell{width:600px; }
#divv{height:80px;overflow:hidden;}

.pczt_pingfen_jhxs_news1{ width:320px;  background:#edfafd; padding-top:2px; padding-bottom:2px; margin:0 auto;}
.pczt_pingfen_jhxs_xian{ width:320px;  margin:0 auto; border:1px dashed #a8d1dd; border-left:none; border-right:none;}
.pczt_pingfen_jhxs_noxian{ width:320px;  margin:0 auto; border:none;}
.pczt_pingfen_jhxs_wenzi{color:#185881; text-align:center; line-height:30px;}
.pczt_pingfen_jhxs_wenzi2{line-height:22px; font-size:12px; text-indent:2em; color:#185881;}
</style>
<script type="text/javascript" src='/js/score.js'></script>
<script src="/files/log.js" async="" charset="utf-8"></script><script src="/files/key.htm"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<link rel="stylesheet" href="/files/style.css">
    <script src="/files/jquery-1.js" type="text/javascript"></script>
    <script type="text/javascript">
    var jq=jQuery.noConflict();
    </script>
<script type="text/javascript">
function opennew(id,scid)
{
window.open("/news/showone?scid="+scid+"&id="+id,null,"width=700,height=400,toolbar=no,top=100,left=400,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no")
}
function openw(id)
{
window.open("/school/showone?id="+id,null,"width=700,height=400,toolbar=no,top=100,left=400,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no")
}
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-100524-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<body>
<style type="text/css">

#head_wrap{ width:950px; margin:0 auto; clear:both; font:12px/1.5 '\5FAE\8F6F\96C5\9ED1','\5B8B\4F53', Arial, Helvetica, sans-serif; background:#fff; padding:0 10px;}
ul, li{ margin:0; padding:0;}
div.header_all{ height:32px; width:950px;font-size:12px; background:#FFF url('http://t1.chsi.cn/yz//images/common/header_topbg01.gif') repeat-x bottom;  margin:0px auto;clear:both; color:#333333;}
.header_all li a,.header_all li a:link,.header_all li a:visited{ color:#333333; text-decoration:none;}
.header_all li a:hover{ color:#990000; text-decoration:underline;}
.header_all ul{ width:950px; height:27px; background:url('http://t4.chsi.cn/yz//images/common/header_topbg02.gif') no-repeat right;}
.header_all ul li{height:27px;line-height:30px; float:left; display:inline; background:url('http://t4.chsi.cn/yz//images/common/header_topbg02.gif') no-repeat left; padding:0px 9px 0px 10px !important; text-align:center; overflow:hidden;}
#head_wrap h1{width:536px; height:76px; float:left; display:inline;font-size:1px; color:#FFF; line-height:160px; overflow:hidden; background:url('/images/logologinn.png') no-repeat 0 25px; position:relative;}
#head_wrap h1 a{ display:block; width:536px; height:76px; line-height:76px; position:absolute; top:0; left:0;}
#head_wrap h1 a:hover{ text-decoration:none;}
.h_box{width:400px; height:76px; float:right; position:relative; background:#fff;}
.h_login_user{ position:absolute; top:0; right:0; width:640px; height:42px; line-height:42px; overflow:hidden;text-align:right;}
.h_r_all{ position:absolute; top:42px; right:0;width:400px; height:25px;}
.h_login_btn{height:23px; line-height:23px;float:right; margin-left:10px; padding:0 10px; border:1px solid #DDD; background:url('http://t4.chsi.cn/yz//images/index/ban_bg2013.png') no-repeat 0 -84px;}
.h_search{float:right; margin-left:10px;border:1px solid #DDD;}
.h_search input.h_s_txt{ height:23px; line-height:23px; border:none; padding:0 3px; background:#FFF; width:144px; float:left;}
.h_search input.h_s_submit{height:23px; line-height:23px;border:none; border-left:1px solid #DDD; background:url('http://t1.chsi.cn/yz//images/index/ban_bg2013.png') no-repeat 0 -84px; width:40px; float:left; cursor:pointer;}

#head_wrap div.h_nav_box{ width:950px; height:40px; background:#2D72B0 url('http://t2.chsi.cn/yz//images/index/nav_bg2013.png') no-repeat; margin-bottom:0px;clear:both;}
.h_nav{ width:950px; height:38px; line-height:38px; text-align:center; color:#FFFFFF;}
.h_nav a,.h_nav a:link,.h_nav a:visited{color:#FFFFFF;}
.h_nav a:hover{ color:#FF9;}
.h_nav_sub{height:30px; line-height:30px; text-align:left;}
</style>

<style type="text/css">
.adminLogin{width:100px;float:right;display:inline;height:22px;display:inline;margin:5px 10px 0 0;}
.login{float:left;display:inline;height:22px;display:inline;margin:5px 10px 0 325px;overflow:hidden;text-align:right;}
.loginTXT{border:1px solid #ccc;width:80px;height:16px;line-height:16px;}
.loginTXT:hover{border:1px solid #9cf;}
.loginBTN{border:0;background:url('http://t3.chsi.cn/yz//images/common/login.jpg') no-repeat;width:35px;height:20px;}
.color1 {    color: #BA2636 !important;}
.color2 {    color: #0068A3 !important;}
.color3 {    color: #FF3300 !important;}
</style>
<div id="head_wrap">
  <div class="header_all">
    <ul>
      <li><a href="http://www.chsi.com.cn/" target="_blank">学信网</a></li>
    <li><a href="http://xjxl.chsi.com.cn/" target="_blank">学籍查询</a></li>
    <li><a href="http://www.chsi.com.cn/xlcx/" target="_blank">学历查询</a></li>
    <li><a href="http://www.chsi.com.cn/xlcx/bgcx.jsp" target="_blank">在线验证</a></li>
    <li><a href="http://www.chsi.com.cn/cet/" target="_blank">四六级查分</a></li>
    <li><a href="http://www.gfbzb.gov.cn/" target="_blank">征兵报名</a></li>
    <li><a href="http://job.chsi.com.cn/" target="_blank">就业</a></li>
    
    </ul>
  </div>
  <h1>吉林研究生推免信息网<a href="/">&nbsp;</a></h1>
  <div class="h_box">
      
    
    

    <div class="h_r_all">
        <form method="get" action=""  name="searchinfo" class="h_search">
        <input name="q" type="text" class="h_s_txt"  value="站内搜索" onclick="if(this.value=='站内搜索')this.value=''" />
      
      </form>
      <script type="text/javascript">
function checkSearch(){
if (searchinfo.q.value == "站内搜索") {
searchinfo.q.value = "";
}
return true;
}
</script>  
    <div class="h_login_btn"><a target="_self" href="/login/manlogin">管理部门登录</a></div>  
    <div class="h_login_btn"><a target="_self" href="/login/login">考生登录</a></div>  
  </div>
  </div>
  <div class="h_nav_box">
  <div class="h_nav">友情连接： <a href="http://yz.chsi.cn/yzzt/jskx_jx2014" target="_blank">计算机考研分析</a>　| 　<a href="http://yz.chsi.cn/kyzx/zcdh/" target="_blank">政策</a>　<a href="http://yz.chsi.cn/kyzx/zcdh/201308/20130813/471774590.html" target="_blank">国家助学金</a>　
  <a href="http://yz.chsi.cn/kyzx/zcdh/201308/20130812/466965194.html" target="_blank">学业奖学金</a>　
 
  <a href="http://www.chsi.com.cn/cet/" target="_blank">四六考试</a>　<a href="http://yz.chsi.cn/z/yzmba/index.jsp" target="_blank">MBA</a>
  <a href="http://yz.chsi.cn/z/yzzyss/index.jsp" target="_blank">专业硕士</a><sup><img src='http://t1.chsi.cn/yz/images/common/dot_hot.jpg' width="6" height="6" /></sup>　</div>
  
 
  
  
  </div>
  </div>
  
  
<div>
  <table width="70%" align=center border="0" bordercolordark="#ffffff" bordercolorlight="#FFCCFF"  cellspacing="3">
  <tr>
    <td width="27%" height="192"><!--幻灯片加载11111111111111111111111111111111111111111111111111111-->
	   <div class="main">
<div class="hometop"></div>
<div class="honmmid">
<!--主体上部-->
<div class="maintop" >
    <!--主体左上部-->
    <div class="top_left">
        <div id="container">
            <div style="overflow: hidden; " id="slider" >
            <?php foreach ($this->scs as $item){   
          	$scname=$item['scname'];
          	$pic=$item['pic'];
          	$scid=$item['scid'];
          	echo "<div style='position: absolute; top: 0px; left: -300px; display: none; z-index: 6; opacity: 1; height: 277px; width: 300px;' class=sliderItem id=slide1>
                    <h2><a href= target=_blank >$scname</a></h2>
                    <a href='#' style='color:#0000FF' onClick=openw('$scid')><img src=/upload/$pic  height=170px width=285px></a>
                </div>" ;
}?>
                 
				 
            </div>
          <!-- /slider -->
          <div id="sliderNav">
            <div class="sliderNav_left">
              <a href="#" class="previous">Previous</a>
              <a href="#" class="next">Next</a>
              <div class="siderCon"><ul></ul></div>
            </div>
          </div>
        </div>

    </div>
    <!--主体左上部-->

    
</div>
<!--主体上部-->
</div>
</div>
<script src="/files/jscode.js" type="text/javascript"></script>


	<!--幻灯片加载11111111111111111111111111111111111111111111111111111-->	</td>
    <td width="40%">
       <!-- 222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222 -->
        <table width="430" border="0" align="center" cellpadding="4" cellspacing="1" style="background-color:#AAA;text-align:left">
      <tr bgcolor="#00ffff">
        <th colspan="5" align="center" height="25" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">推免高校访问量排名</th>
      </tr>
      <tr bgcolor=#FFFFFF>
        <th bgcolor=#ffffff>学校名称</td>
        <th bgcolor=#ffffff>学校类型</td>
        <th bgcolor=#ffffff>参考分数</td>
        <th bgcolor=#ffffff>访问量</td>
        <th bgcolor=#ffffff>详情</td>
      </tr>
     <?php foreach ($this->scs as $item){   
          	$id=$item['scid'];
          	$dy=$item['dyscore'];
          	$zy=$item['zyscore'];
          	$sum=$item['sumscore'];
          	
      echo "        
      <tr bgcolor=#FFFFFF>
        <td bgcolor=#ffffff>".$item['scname']."</td>
        <td bgcolor=#ffffff>".$item['sctype']."</td>
        <td bgcolor=#ffffff>";
        echo "德育:_".$dy.";  智育:_".$zy.";  总分:_".$sum;
        echo "</td>
        <td bgcolor=#ffffff>".$item['clip']."</td>
        <td bgcolor=#ffffff style=color:#FF3300><a href='#' style='color:#0000FF' onClick=openw('$id')>查看</a></td>
        
        </tr>";
      }?> 
</table>
  <!-- 222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222 -->
    </td>
    <td width="35%">
    <!-- 55555555555555555555555555555555555555555555555555555555555555 -->
       <table width="100%" border=0 bordercolordark="#ffffff" bordercolorlight="#FFCCFF"  cellspacing="3" >
        <tr bgcolor="#00ffff"><th align="center" height="25" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">推免成功学生公示</th></tr>
        <tr ><td><font color=blue>_序号_&nbsp;推免号&nbsp;_姓名    <br/>推免高校</font></td></tr>
        <tr><td>
        <span class="shell">
          
	<div id="divv">
	 <?php 
	 $s=0;
	 foreach ($this->stus as $item){
        $s++;
	 	echo "<a href=><font color=blue>_".$s."_</font>&nbsp;".$item['id']."_".$item['name']."<br/>".$item['tmresult']."</a><br/>";
	 }?>
	  
	 
	</div>
        </span>
        
        </td></tr>
       </table>
    <!-- 55555555555555555555555555555555555555555555555555555555555555 -->
    </td>
     
  </tr>
  <tr>
    <td><!-- 3333333333333333333333333333333333333333333333333333333333333333333333 -->
    <div id="demo" onmouseover="clearInterval(timer)" onmouseout="timer=setInterval(mar,30)" style="overflow:hidden; height:180px; width:100%;">
<div id="demo1" style="height:100%;" >
           			<div class="pczt_pingfen_jhxs_news1" >
                    	<div class="pczt_pingfen_jhxs_xian">
                        	
                            <p class="pczt_pingfen_jhxs_wenzi">
							    <table width="100%">
     <tr bgcolor="#00ffff"><td colspan=3 align="center" height="25"  style="font-size:14px; font-weight:600; letter-spacing:2px;">高校研究生推免最新消息</td></tr>
       <?php foreach ($this->news as $item){
       	$id=$item['id'];
       	$scid=$item['scid'];
	echo "
  <tr>
    <td align=left><a href='#' style='color:#0000FF' onClick=opennew('$id','$scid')>".$item['title']."</a></td>
	<td>&nbsp;</td>
    <td> ".$item['time']."</td> 
  </tr>
  ";

  }?>
    
    
    </table>
							
							</p>
                        </div>
                    </div>
                    <div class="pczt_pingfen_jhxs_xian">
                      
                      <p class="pczt_pingfen_jhxs_wenzi">
					     <table width="100%">
        
       <?php foreach ($this->news as $item){
       	$id=$item['id'];
	echo "
  <tr>
    <td align=left><a href='#' style='color:#0000FF' onClick=opennew('$id')>".$item['title']."</a></td>
	<td>&nbsp;</td>
    <td> ".$item['time']."</td> 
  </tr>
  ";

  }?>

    </table>					  
					  </p>
                    </div>
          <div id="demo2"></div>
          </div>
			</div>
    
     <!-- 3333333333333333333333333333333333333333333333333333333333333333333333333333333 --></td>
    
    <td bgcolor="#aaffff">
      <!-- tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt -->
         
       <img src="/graph/line.php"   border=1  width =380 height=170>

         
      <!-- tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt -->
    </td>
    <td>
    <!-- 22-22-22-22-22-22-22-22-22- -->
         <table>
            <tr><td><hr color="#00ffff"></td></tr>
            <tr bgcolor="#00ffff"><td align="center" height="25" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">按学校查询专业</td></tr>
            <tr><td><select class="l_form_width02"  onchange=sdept(this.value) >
     <option>----请选择学校----</option>
      <?php foreach ($this->scss as $item){  
                	echo "<option>".$item['scname']."</option>";
                }?>
    </select><select id="ttt" class="l_form_width02" style="width:174px; overflow:hidden;">
      <option value="" selected="selected">对应的专业</option>
    </select>
     
    </td></tr>
    <tr><td><hr color="#00ffff"></td></tr>
     <tr bgcolor="#00ffff"><td align="center" height="25" valign="middle" style="font-size:14px; font-weight:600; letter-spacing:2px;">按专业查询学校</td></tr>
            <tr><td><select class="l_form_width02"  onchange=sclist(this.value) >
            <option>----请选择专业----</option>
       <?php foreach ($this->sdepts as $ite){
            	$it=$ite['name'];
            	$id=$ite['id'];
            echo "<option value=$id>$it</option>";
            }?>
    </select><select  id="tt" class="l_form_width02" style="width:174px; overflow:hidden;">
      <option value="" selected="selected">对应的学校</option>
    </select>
    
    
    
    
    
    </td></tr>
    <tr><td><hr color="#00ffff"></td></tr>
         </table>
         
         
         
        <!-- 22-22-22-22-22-22-22-22-22- -->
    
    
    </td>
  </tr>
  
  <tr><td colspan=3><hr></td></tr>
 
</table>

</div>


<div class="footer" id="footer" align="center"> <a href="" target="_blank">[ CHSI首页 ]</a> -- <a href="" target="_blank">[ 中心简介 ]</a> -- <a href="" target="_blank">[ 联系我们 ]</a> 
-- <a href="" target="_blank">[ 版权声明 ]</a> -- <a href="" target="_blank">[ 网站地图 ]</a> -- <a href="" target="_blank">[ 宣传代理 ]</a> -- <a href="" target="_blank">[ 我要投稿 ]</a> <br />
    主管单位：高校研究生推免管理委员会　　主要设计：<a href="" target="_blank">长春大学计算机学院单智</a>　　<a href=""  target="_blank">学号：271040219</a><br />
   主要内容：吉林省计算机类研究生推免管理系统　　服务热线：15543261882　　　邮箱：421170702@qq.com</div>
<div style="z-index: 100; left: 1px; position: absolute; top: 50px; width:102px; height:320px; overflow:hidden;">
<script type="text/javascript">showShortCut('534729923')</script>
</div>
<div style="z-index: 100; right: 1px; position: absolute; top: 50px; width:102px; height:320px; overflow:hidden;">
<script type="text/javascript">showShortCut('534733763')</script> 
</div>
</body>
</html>
<script>
var t=getid("demo"),t1=getid("demo1"),t2=getid("demo2"),sh=getid("show"),timer;
t2.innerHTML=t1.innerHTML;
function mar(){
if(t2.offsetTop<=t.scrollTop)
t.scrollTop-=t1.offsetHeight;
else
t.scrollTop++;
}
timer=setInterval(mar,30);
function getid(id){
return document.getElementById(id);
}
</script>
<script>
var c,_=Function;
with(o=document.getElementById("divv")){ innerHTML+=innerHTML; onmouseover=_("c=1"); onmouseout=_("c=0");}
(F=_("if(#%18||!c)#++,#%=o.scrollHeight>>1;setTimeout(F,#%18?15:400);".replace(/#/g,"o.scrollTop")))();
</script>
