<!DOCTYPE HTML>
<html>

<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
</head>

<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #F8F9FA;
}
-->
</style>
<?php $name=$this->pscname;
$attendtag=$this->attendtag;
?>

<script type="text/javascript">
  
  function print(){
	  window.location.href="../php/applyprint.php?scname=<?php echo $name?>"; 
  }
  function attend(){
	  if(<?php echo $attendtag?>=='1'){
         window.location.href="/apply/send";
	  }else{
		  if (confirm("需先发布录取分数分数线，现在前往？")) {
			  window.location.href="/news/write"; 
		  }
	  }
  }
</script>

<link href="/images/skin.css" rel="stylesheet" type="text/css" />
<body>

<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
  <tr>
    <td width="17" height="29" valign="top" background="/images/mail_leftbg.gif"><img src="/images/left-top-right.gif" width="9" height="29" /></td>
    <td width="935" height="29" valign="top" background="/images/content-bg.gif"><table width="100%" height="31" border="0" cellpadding="0" cellspacing="0" class="left_topbg" id="table2">
     <tr>
        <td height="31"><div class="titlebt">推免管理</div></td>
      </tr>
    </table></td>
    <td width="16" valign="top" background="/images/mail_rightbg.gif"><img src="/images/nav-right-bg.gif" width="16" height="29" /></td>
  </tr>
  <tr>
    <td height="71" valign="middle" background="/images/mail_leftbg.gif">&nbsp;</td>
    <td valign="top" bgcolor="#F7F8F9"><table width="100%" height="138" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td height="13" valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top">
		    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td class="left_txt">推免管理:&nbsp;&nbsp;<input type="button" value="打印成绩单" onclick="print()">
            
                  &nbsp;&nbsp;<input type="button" value="发送录取通知" onclick="attend()">
            </td>
          </tr>
         
          
          <tr>
            <td><hr color="#CCCCCC"></td>
          </tr>
         
          <tr>
            <td>
			<form name="f" method="POST" action="/apply/addscore">
			<table width="90%" border="1" cellspacing="0" cellpadding="0" align="center" bordercolor="#FFFFFF">
			  <tr><td colspan=7 class="left_bt2" align=center bgcolor='#f2f2ff'>推免生笔试面试综合推荐分数</td></tr>
              <tr>
                <td width="15%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">学生号</td>
				<td width="10%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">姓名</td>
				<td width="15%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">推免专业</td>
                <td width="18%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">推荐分数</td>
                <td width="18%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">笔面试分数&nbsp;&nbsp;&nbsp;
                <input type="submit" value="录入成绩">
                </td>
                <td width="15%" height="30" bgcolor="#f2f2f2" class="left_txt">总分&nbsp;&nbsp;&nbsp;排名</td>
				<td width="10%" height="30" align="left" bgcolor="#f2f2f2" class="left_txt2">备注</td>
              </tr>
              <?php $i=0;?>
			  <?php foreach ($this->apply as $item){
			  	$id=$item['applyid'];
			  	$sdename=$item['sdename'];
			  	$stuid=$item['stuid'];
			  	$stuname=$item['stuname'];
			  	$dy=$item['dyscore'];
			  	$zy=$item['zyscore'];
			  	$sum=$dy+$zy;
			  	$sumscore=$item['sumscore'];
			  	$bs=$item['bscore'];
			  	$ms=$item['mscore'];
			  	$tag=$item['tag'];
			  	if($tag=="3"){
			  		$state="<font color=red size=-2>待录取";
			  	}else if($tag=="2"){
			  		$state="<font color=gray size=-2>未录取</font>";
			  	}else if($tag=="4"){
			  		$state="<font color=gray size=-2>已录取</font>";
			  	}else if($tag=="5"){
			  		$state="<font color=gray size=-2>被拒绝</font>";
			  	}else{
			  		$state="<font color=gray>待审查</font>";
			  	}
			  	$bz=$item['bz'];
			  	$i++;
			  	
			  	echo "
              <tr>
                <input type=hidden name=ids[] value=$id>
                <td width=15% height=30 align=left bgcolor=#f2f2f2 class=left_txt2>$stuid</td>
				<td width=10% height=30 align=left bgcolor=#f2f2f2 class=left_txt2>$stuname</td>
				<td width=15% height=30 align=left bgcolor=#f2f2f2 class=left_txt2>$sdename</td>
                <td width=18% height=30 align=left bgcolor=#f2f2f2 class=left_txt2><font color=blue>德育:_$dy;  智育:_$zy;  总分:_$sum</font></td>
                <td width=18% height=30 align=left bgcolor=#f2f2f2 class=left_txt2>
                                                               笔试:<input type=text name=bss[] style=height:10px size=1 value=$bs>
				       面试:<input type=text name=mss[] style=height:10px size=1 value=$ms> </td>
                <td width=15% height=30 bgcolor=#f2f2f2 class=left_txt>$sumscore &nbsp;&nbsp;第&nbsp;$i&nbsp;名</td>
				<td width=10% height=30 align=left bgcolor=#f2f2f2 class=left_txt2>$state</td>
				
              </tr>";
              }?>
            </table>
		  </form>
		 </td>
          </tr>
          <tr>
            <td><hr color="#CCCCCC"></td>
          </tr>
        </table>
		
		
         </td>
      </tr>
    </table></td>
    <td background="/images/mail_rightbg.gif">&nbsp;</td>
  </tr>
  <tr>
    <td valign="middle" background="/images/mail_leftbg.gif"><img src="/images/buttom_left2.gif" width="17" height="17" /></td>
      <td height="17" valign="top" background="/images/buttom_bgs.gif"><img src="/images/buttom_bgs.gif" width="17" height="17" /></td>
    <td background="/images/mail_rightbg.gif"><img src="/images/buttom_right2.gif" width="16" height="17" /></td>
  </tr>
</table>

</body>
