<!DOCTYPE HTML>
<html>
<head>
		<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
</head>
<title>用户登录</title>
<link rel="stylesheet" type="text/css" href='/css/a.css'/>
<link rel="stylesheet" type="text/css" href='/css/b.css'/>
<link rel="stylesheet" type="text/css" href='/css/c.css'/>

<script src="/js/alterstupw.js"></script>
<script type="text/javascript">
	function reback(){
		window.location.href="/student/stuenter";
	}

    function checkpw(){
    	var opw=document.f.opw.value;
    	if(opw==""){
           alert("请输入原密码，才能修改");
        }
        if(document.f.pw.value!==document.f.pwx.value){
           alert("新密码需与原密码一致");
           document.f.pwx.value="";
        }
    }

    function remove(){
    	
        var info=document.getElementById("txtHint").innerText;   
        if(info.trim()=='原密码错误'){
        	document.f.opw.value="";
        }          
    }
    
    

</script>
<body>

<style type="text/css">
#head_wrap {
    clear: both;
	background:#fff;
    font: 12px/1.5 '微软雅黑','宋体',Arial,Helvetica,sans-serif;
    margin: 0 auto;
    padding: 0 10px;
    width: 950px;
}
#head_wrap h1 {
    background: url("/images/logologinn.png") no-repeat scroll 0 25px transparent;
    color: #FFFFFF;
    font-size: 1px;
    height: 76px;
    line-height: 160px;
    overflow: hidden;
    position: relative;
    width: 536px;
}
#head_wrap h1 a {
    display: block;
    height: 76px;
    left: 0;
    line-height: 76px;
    position: absolute;
    top: 0;
    width: 536px;
}
#head_wrap h1 a:hover {
    text-decoration: none;
}
</style>
<div id="head_wrap">
  <h1>中国研究生招生信息网<a href="/">&nbsp;</a></h1>
</div>
  <div id="content" class="container_24 clearfix">
  <div class="clearfix" id="user_box">
  <div class="user-bh">
      <div class="yz_loginAfter">欢迎您，<a href="javascript:void(0)"><?php echo $this->id?>_<?php echo $this->name?></a> &nbsp;&nbsp; <a href="/global/exit" target="_self">安全退出</a>&nbsp;&nbsp; <a href="/student/stuenter" target="_self">返回</a></div>
      <h2>用户中心</h2>
    </div>
  <div class="user-bd">
  <div class="resetpwd">
  <h3>修改密码</h3>
  <form name="f" method="post" action="/student/stualterpw"> 
 <table width="80%" border="0" cellpadding="4" cellspacing="1">
    <tr>
              <td width=30% class="text_right">输入原密码：</td>
              <td width=40% align="left"><input type="password" name="opw" onkeyup="showHint(this.value)" required="required" maxlength="14" size="14" class="bbsInput_short">
              <td width=30% ><span style="color:#0000ff;" id="txtHint"></span></td>
            </tr>

    <tr>
              <td class="text_right">输入新密码：</td>
              <td align="left"><input type="password" name="pw" required="required" onfocus="remove()" pattern="^[a-zA-Z0-9]{4,8}$" title="密码由4至8位的字母或数字组成" maxlength="14" size="14" class="bbsInput_short">
              <td></td>
            </tr>
            <tr>
              <td class="text_right">确认新密码：</td>
              <td align="left"><input type="password" name="pwx" required="required" onChange="checkpw()" title="需与原密码一致" value="" size="14" maxlength="14" name="repassword" class="bbsInput_short" ></td>
              <td></td>
           </tr>
    <tr>
    <td height="40" class="text_right"><input type="hidden" name="ss" value="1"></td>
      <td height="40"  align="left">
      
      

      <br>
         <input type="button" value="返 回" onclick="reback()"  class="buttonSel"> &nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" value="确 认" class="buttonDeep">&nbsp;
      </td>
    </tr>
  </table>
</form>


  </div>
  </div>
  </div>
  </div>
  </div>
  


<hr/>
<div align=center>
<iframe width="950" height="93" src="/index/foot" scrolling="no" frameborder="0"></iframe>
</div>


</body>
</html>
